import { NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import { prisma } from '@/lib/prisma';

export async function GET() {
  try {
    const schools = await prisma.school.findMany({
      orderBy: { createdAt: 'desc' },
    });
    return NextResponse.json(schools);
  } catch (error) {
    return NextResponse.json({ message: 'Failed to fetch schools' }, { status: 500 });
  }
}

async function generateSchoolId(): Promise<string> {
  const last = await prisma.school.findFirst({
    where: { schoolId: { startsWith: 'MITT' } },
    orderBy: { schoolId: 'desc' },
    select: { schoolId: true },
  });
  const lastNum = last ? parseInt(last.schoolId.replace('MITT', ''), 10) : 0;
  const nextNum = (isNaN(lastNum) ? 0 : lastNum) + 1;
  return `MITT${String(nextNum).padStart(3, '0')}`;
}

function generatePassword(length = 10): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789abcdefghijkmnpqrstuvwxyz';
  let out = '';
  for (let i = 0; i < length; i++) {
    out += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return out;
}

function buildOlympiadIdPrefix(crmId: string, schoolName: string): string {
  const crm = crmId.replace(/[^A-Za-z0-9]/g, '').slice(0, 6).toUpperCase();
  const nm = schoolName.replace(/[^A-Za-z0-9]/g, '').slice(0, 4).toUpperCase();
  // prefix = crm + nm, max 10 chars so 2-digit number always fits to make 12
  return (crm + nm).slice(0, 10);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      name,
      olympiadId,
      address,
      email,
      phone,
      contactPerson,
      city,
      state,
      pincode,
      studentCount,
    } = body;

    if (!name || !olympiadId) {
      return NextResponse.json(
        { message: 'School name and CRM ID are required' },
        { status: 400 }
      );
    }

    const count = parseInt(studentCount || '0', 10);
    if (!count || count < 1 || count > 2000) {
      return NextResponse.json(
        { message: 'Student count must be between 1 and 2000' },
        { status: 400 }
      );
    }

    // Generate schoolId with retry on race condition
    for (let attempt = 0; attempt < 3; attempt++) {
      const schoolId = await generateSchoolId();
      const plainPassword = generatePassword(10);
      const hashedPassword = await bcrypt.hash(plainPassword, 10);

      try {
        // Create school
        const school = await prisma.school.create({
          data: {
            schoolId,
            olympiadId,
            name,
            address,
            email,
            phone,
            contactPerson,
            city,
            state,
            pincode,
            username: schoolId,
            password: hashedPassword,
            plainPassword: plainPassword,
          },
        });

        // Auto-generate Olympiad IDs
        const prefix = buildOlympiadIdPrefix(olympiadId, name);
        const padLen = count > 999 ? 4 : count > 99 ? 3 : 2;
        const now = new Date();

        const olympiadIds = Array.from({ length: count }, (_, i) => {
          const seq = i + 1;
          const numStr = String(seq).padStart(padLen, '0');
          const code = (prefix + numStr).slice(0, 12);
          return {
            code,
            prefix,
            sequence: seq,
            schoolId: school.id,
            sentAt: now, // auto-sent since generated by admin at registration
          };
        });

        await prisma.olympiadIdAllocation.createMany({
          data: olympiadIds,
          skipDuplicates: true,
        });

        return NextResponse.json({
          ...school,
          olympiadIdsGenerated: count,
          olympiadIdPrefix: prefix,
          credentials: {
            username: schoolId,
            password: plainPassword,
          },
        });
      } catch (err: any) {
        if (err?.code === 'P2002' && attempt < 2) continue;
        throw err;
      }
    }

    return NextResponse.json({ message: 'Could not allocate schoolId' }, { status: 500 });
  } catch (error) {
    console.error('POST /api/schools failed:', error);
    return NextResponse.json({ message: 'Failed to create school' }, { status: 500 });
  }
}
